name = "savaspinapp-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=savaspinapp.com.gr"
HMAC_KEY = "cb61de5a4ce8c79f61193a113d934c7bcc077cacbd8abc74651c75a59675ceb7"
COOKIE_NAME = "xwg"
PLAY_PATH = "start"
BUTTON_ID = "p03c483f3a5bc9825912c52c7e919fa2e"
GATE_SALT = "4db00c3d2e29539f"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ng06"
CTA_SELECTOR = ".play-button"
